#ubuntu servers
[linux]
ansible-con ansible_host=10.10.10.30 ansible_user=ansible-con
log01       ansible_host=10.10.10.40 ansible_user=log01
#windows machines
[windows]
dc01 ansible_host=10.10.10.10
cl01 ansible_host=10.10.10.20
#winrm
[windows:vars]
ansible_connection=winrm
ansible_port=5985
ansible_winrm_transport=basic
ansible_winrm_server_cert_validation=ignore
ansible_user=student
ansible_password=Team123!

