#linux servers
[linux]
ansible-con ansible_host=10.10.10.30 ansible_user=ansible-con
#windows servers
[windows]
dc01 ansible_host=10.10.10.10 ansible_user=student ansible_password=Team123!
cl01 ansible_host=10.10.10.20 ansible_user=student ansible_password=team
#winrm
[windows:vars]
ansible_connection=winrm
ansible_port=5985
ansible_winrm_transport=basic
ansible_winrm_server_cert_validation=ignore

