#windows serverit
[windows]
dc01 ansible_host=10.10.10.20
cl01 ansible_host=10.10.10.30
#winrm
[windows:vars]
ansible_connection=winrm
ansible_port=5985
ansible_winrm_transport=basic
ansible_winrm_server_cert_validation=ignore
ansible_user=BlueTeam
ansible_password=passwd

#user ja password on vaan mitä tein tätä varten voi muuttaa
